config/routes.rb
Rails.application.routes.draw do

  devise_for :members, path: '', path_names: {sign_in: '/login', sign_out: '/logout', sign_up: '/signup'}, controllers: { registrations: 'registrations' }

  
  post 'upload-receipt/:id' => 'transaction#upload_receipt', :as => :upload_receipt

  get 'transactions' => 'transaction#list', :as => :transactions
  get 'disputes' => 'transaction#disputes', :as => :disputes

  get 'transaction-receipt/:id' => 'transaction#receipt', :as => :receipt
  get 'dispute/:id' => 'transaction#dispute', :as => :dispute
  get 'transaction/:id' => 'transaction#show', :as => :transaction
  get 'transaction/:id/send-money' => 'transaction#send_money', :as => :send_money
  get 'transaction/:id/reject' => 'transaction#reject', :as => :reject
  get 'transaction/:id/confirm' => 'transaction#confirm', :as => :confirm
  get 'transaction/:id/settle' => 'transaction#settle', :as => :settle

  # Dashboard
  get  'dashboard' => 'dashboard#index', :as => :dashboard
  post 'setting' => 'dashboard#setting', :as => :setting
  get  'members' => 'dashboard#members', :as => :members
  get  'groups' => 'dashboard#groups', :as => :groups

  # Account
  get  'account/add' => 'account#add', :as => :add_account
  get  'account/:id/kick-out' => 'account#kick_out', :as => :kick_out
  post 'account/change-pool-order/:id' => 'account#change_pool_order', :as => :change_pool_order

  # Member
  post 'member/increase-accounts-limit/:id' => 'member#increase_accounts_limit', :as => :increase_accounts_limit
  get  'member/:id/edit' => 'member#edit', :as => :edit_member
  post 'member/:id' => 'member#update', :as => :update_member
  get  'member/:id' => 'member#show', :as => :member
  get  'member/:id/lock' => 'member#lock', :as => :lock_member
  get  'member/:id/complete' => 'member#complete', :as => :complete_member
  get  'add-super-user' => 'member#add_super_user', :as => :add_super_user
  
  get  'add-group' => 'member#add_group', :as => :add_group
  get  'edit-group/:id' => 'member#edit_group', :as => :edit_group
  post  'save-group' => 'member#save_group', :as => :save_group
  post  'update-group/:id' => 'member#update_group', :as => :update_group
  post  'save-super-user' => 'member#save_super_user', :as => :save_super_user

  get  'add-admin' => 'member#add_admin', :as => :add_admin
  post  'save-admin' => 'member#save_admin', :as => :save_admin


  # Pool
  get  'add-pool' => 'pool#add', :as => :add_pool
  post 'save-pool' => 'pool#save', :as => :save_pool
  get  'pool/:id/edit' => 'pool#edit', :as => :edit_pool
  post 'pool/:id/update' => 'pool#update', :as => :update_pool





  # Home
  get  'support' => 'home#support', :as => :support
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_member!

  def index
    if current_member.super_admin?
      @current_account = nil
      @groupements     = Groupement.includes(:pools => :accounts).all
      @members         = Member.all
    else 
      @groupements = [current_member.groupement].compact if current_member.group_admin?
      if @current_account.present?
        @transaction_history  = @current_account.transaction_history
        @current_transactions = @current_account.pending_transactions
        @current_transaction  = @current_transactions.pop
      end
    end
  end

  def members
    if current_member.super_admin?
      @members = Member.all
    elsif current_member.group_admin?
      @members = current_member.groupement.members rescue []
    end
  end

  def groups
    if current_member.super_admin?
      @groupements = Groupement.includes(pools: :accounts).all
    elsif current_member.group_admin?
      @groupements = [current_member.groupement.includes(:pools)].compact
    end
  end

  def setting
    @member = current_member
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def timeout_wording(t)
    distance_of_time_in_words(Date.current.in_time_zone, (t.created_at + t.timeout.seconds))
  end

  def timeout_countdown_old(t)
    (t.created_at + t.timeout.seconds).strftime("%b, %d, %Y")
  end

  def timeout_countdown(t)
    x = []
    (t.created_at + t.timeout.seconds).strftime("%Y, %m, %d, %H, %M, %S, 000").split(",").each_with_index{|a,i| i == 1 ? x << (a.to_i-1) : x << a  }
    x.join(",")
  end  
end

app/views/dashboard/_countdown.html.erb
<%- if t.timed_out? %>
	<script type="text/javascript">
		var countdown = document.getElementById('countdown');
		countdown.innerHTML = "TIMED OUT"
	</script>
<%- else %>
	<script type="text/javascript">
	var target_date = new Date('<%= timeout_countdown(t) %>').getTime();

	var days, hours, minutes, seconds;
	var countdown = document.getElementById('countdown');
	setInterval(function () {
	    var current_date = <%= Time.zone.now.to_datetime.strftime('%Q') %>;
	    var seconds_left = (target_date - current_date) / 1000;
	 

	    hours = parseInt(seconds_left / 3600);
	    seconds_left = seconds_left % 3600;
	     
	    minutes = parseInt(seconds_left / 60);
	    seconds = parseInt(seconds_left % 60);

	    countdown.innerHTML = '<span class="hours">' + hours + '</span>:<span class="minutes">' + minutes + '</span>:<span class="seconds">' + seconds + '</span>';  
	 
	}, 1000);
	</script>
<%- end %>

app/views/dashboard/_current.html.erb
<div class="col-md-12 m-b-10">
  <div class="widget-item ">
    <%- if current_member == current_transaction.feeder.member %>
      <%= render 'dashboard/sections/sender', current_transaction: current_transaction %>
    <%- else %>
      <%= render 'dashboard/sections/receiver', current_transaction: current_transaction %>
    <%- end %>
  </div>
</div>

app/views/dashboard/_current_transaction.html.erb
          <div class="col-md-12 m-b-10">
            <div class="widget-item ">
              <div class="controller overlay right">
                <a href="javascript:;" class="reload"></a>
                <a href="javascript:;" class="remove"></a>
              </div>
              <div class="tiles" style="border: 2px solid #F15152;background-color:#fff">
                <div class="tiles-body">
                  <h3 class="text-black"> <span class="semi-bold"><%= distance_of_time_in_words(DateTime.now, (DateTime.now + @current_transaction.timeout.seconds)) %> </span> to send <span class="semi-bold"><%= number_to_currency @current_transaction.value %></span> </h3>
                  <div class="overlayer bottom-right fullwidth">
                    <div class="overlayer-wrapper">
                      <div class=" p-l-20 p-r-20 p-b-20 p-t-20">
                        <div class="pull-right"> 
                          <a href="<%= transaction_path(@current_transaction) %>" class="btn btn-default"> 
                            <i class="fa fa-search-plus "></i>
                            show detail 
                          </a>
                          <span class="text-black">&nbsp; or &nbsp;</span>
                          <a href="<%= send_money_path(@current_transaction) %>" class="btn text-uppercase btn-primary btn-lg"> 
                            send money now 
                            <i class="fa fa-chevron-circle-right "></i>
                          </a> 
                        </div>
                        <div class="clearfix"></div>
                      </div>
                    </div>
                  </div>
                  <br>
                </div>
              </div>
              <div class="tiles white border-envelope">
                <div class="tiles-body">
                  <div class="row">

                    <div class="width-30pct">
                      <div class="preview-wrapper font-12 padding-top-5">Transaction timeout at</div>
                      <p class="text-black">
                        <i class="fa fa-clock-o m-r-3"></i>
                        <span><%= (@current_transaction.created_at + @current_transaction.timeout.seconds).to_s(:short) %></span> <br/>
                        
                      </p>
                    </div>

                    <div class="width-30pct">
                      <div class="preview-wrapper font-12 padding-top-5">Transfer to</div>
                      <p class="text-black">
                        <i class="fa fa-bank m-r-3"></i>
                        <span><%= @current_transaction.eater.member.bank.title %></span> <br/>
                        <%= @current_transaction.eater.member.account_number %> <br/>
                        <%= @current_transaction.eater.member.account_holder_name %>
                      </p>
                    </div>

                    <div class="width-30pct">
                      <div class="preview-wrapper font-12 padding-top-5">Contact to</div>
                      <p class="text-black">
                        <i class="fa fa-phone m-r-3"></i>
                        <span><%= @current_transaction.eater.member.phone_number %></span> <br/>
                      </p>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>

app/views/dashboard/_empty.html.erb
          <div class="col-md-12 m-b-10">
            <div class="widget-item ">
              <div class="controller overlay right">
                <a href="javascript:;" class="reload"></a>
                <a href="javascript:;" class="remove"></a>
              </div>
              <div class="tiles" style="background-color:#fff">
                <div class="tiles-body">
                  <h3 class="text-black"> 
                    <span class="semi-bold">Let's start playing!</span> <br/>
                    But first, you need to add an account to continue..
                  </h3>
                  <div class="overlayer bottom-right fullwidth">
                    <div class="overlayer-wrapper">
                      <div class=" p-l-20 p-r-20 p-b-20 p-t-20">
                        <div class="pull-right"> 
                          <a href="<%= add_account_path %>" class="btn text-uppercase btn-primary btn-lg"> 
                            ADD ACCOUNT
                            <i class="fa fa-chevron-circle-right "></i>
                          </a> 
                          <%- if current_member.group_admin? and current_member.groupement.accounts.size.zero? %>
                          <a href="<%= add_super_user_path %>" class="btn text-uppercase btn-primary btn-lg"> 
                            ADD SUPER USER
                            <i class="fa fa-chevron-circle-right "></i>
                          </a>          
                          <%- end %>                 
                        </div>
                        <div class="clearfix"></div>
                      </div>
                    </div>
                  </div>
                  <br>
                </div>
              </div>
            </div>
          </div>

app/views/dashboard/_groups.html.erb
<%- for group in groupements do %>      
  <div class="container paddingBottom-10">
    <h1 class="title block"><%= group.title %></h1>

    <div class="tabbable tabs-left">
      <ul class="nav nav-tabs" role="tablist">
        <%- group.pools.each_with_index do |p,i| %>
          <li class="<%= 'active' if i.zero? %>">
            <a href="#tab-pool-<%= "#{group.id}-#{p.id}" %>" role="tab" data-toggle="tab"><%= p.title %></a>
          </li>            
        <%- end %>
      </ul>
      <div class="tab-content">
        <%- group.pools.each_with_index do |p,i| %>
        <div class="tab-pane <%= 'active' if i == 0 %>" id="tab-pool-<%= "#{p.groupement.id}-#{p.id}" %>">
          <div class="table-responsive">
            <table class="table table-hover table-dash ">
              <thead>
                <tr>
                  <th>Sending</th>
                  <th>Receiving</th>
                  <th>Completed</th>
                </tr>
              </thead>
              <tbody>
                
                <tr>
                  <td>
                    <%- for a in p.accounts.feeder do %>
                    <div class="flex">
                      <figure class="item-img m-r-10">
                        <a href="#"><i class="fa fa-user text-lg"></i></a>
                      </figure>
                      <div class="item-desc">
                        <a href="#">
                          <strong><%= a.member.account_holder_name %></strong>
                        </a><br>
                        <i class="fa fa-credit-card"></i> <%= a.member.bank.title %> | <%= a.member.account_number %>
                      </div>
                    </div>
                    <%- end %>
                  </td>
                  <td>
                    <%- for a in p.accounts.eater.order(:pool_order) do %>
                      <div class="flex">
                      <%= form_tag change_pool_order_path(a) do %>
                        <%= select_tag :pool_order, options_for_select((0..p.accounts.eater.count).to_a, a.pool_order), class: 'form-control', onchange: 'this.form.submit()' %>
                      <%- end %>                         
                        <figure class="item-img m-r-10">
                          <a href="#"> &nbsp; <i class="fa fa-user text-lg"></i></a>
                        </figure>
                        <div class="item-desc">
                          <a href="#">
                            <strong><%= a.member.account_holder_name %></strong>
                          </a><br>
                          <i class="fa fa-credit-card"></i> <%= a.member.bank.title %> | <%= a.member.account_number %>
                        </div>
                      </div>
                    <%- end %>
                  </td>
                  <td>
                    <%- for a in p.accounts.completed do %>
                      <div class="flex">                   
                        <figure class="item-img m-r-10">
                          <a href="#"> &nbsp; <i class="fa fa-user text-lg"></i></a>
                        </figure>
                        <div class="item-desc">
                          <a href="#">
                            <strong><%= a.member.account_holder_name %></strong>
                          </a><br>
                          <i class="fa fa-credit-card"></i> <%= a.member.bank.title %> | <%= a.member.account_number %>
                        </div>
                      </div>
                    <%- end %>
                  </td>                  
                </tr>
                <tr>
                  <td>
                    
                    Amount <i class="fa fa-money"></i> <%= p.amount %>
                  </td>
                  <td></td>
                  <td>
                    <i class="fa fa-edit"></i>
                    <%= link_to "Edit", edit_pool_path(p) %>
                  </td>
                </tr>
                
              </tbody>
            </table>

          </div>
        </div>
        <%- end %>
      </div>
      
    </div>
  </div>
<%- end %>

app/views/dashboard/_no_accounts.html.erb
          <div class="col-md-12 m-b-10">
            <div class="widget-item ">
              <div class="controller overlay right">
                <a href="javascript:;" class="reload"></a>
                <a href="javascript:;" class="remove"></a>
              </div>
              <div class="tiles" style="background-color:#fff">
                <div class="tiles-body">
                  <h3 class="text-black"> 
                    <span class="semi-bold">Let's start playing!</span> <br/>
                    But first, you need to add an account to continue..
                  </h3>
                  <div class="overlayer bottom-right fullwidth">
                    <div class="overlayer-wrapper">
                      <div class=" p-l-20 p-r-20 p-b-20 p-t-20">
                        <div class="pull-right"> 
                          <a href="<%= add_account_path %>" class="btn text-uppercase btn-primary btn-lg"> 
                            ADD ACCOUNT
                            <i class="fa fa-chevron-circle-right "></i>
                          </a> 
                        </div>
                        <div class="clearfix"></div>
                      </div>
                    </div>
                  </div>
                  <br>
                </div>
              </div>
            </div>
          </div>

app/views/dashboard/_recent.html.erb
<div class="col-md-12 m-b-10">
  <dl class="accordion">
    <dt href="#accordion2" aria-expanded="true" aria-controls="accordion2" class="dark-grey js-accordionTrigger">
      <span class="icon-square  text-white">
        <i class="fa fa-exchange"></i>
      </span>
        <a href="" class="is-expanded text-white">RECENT TRANSACTIONS</a>
    </dt>
    <dd class="accordion-content accordionItem is-expanded" id="accordion2" aria-hidden="false">
    <%- for t in @transaction_history do %>
    <%- target = t.eater.member == current_member ? t.feeder : t.eater %>
    <div class="col-md-12 trx-recent-item p-t-10 p-b-10">
      <div class="flex box-border box-inset--small">
          <div class="width-70pt trx-recent-bank">
            <a class="m-b-10" href="">
              <i class="fa fa-user"></i>
              <strong>
                <%= target.member.full_name %>
              </strong>
              (<%= target.name %>)
            </a>

            <i class="fa fa-bank"></i> <%= target.member.bank.try(:title).to_s %><br/>
            <%= target.member.account_holder_name %> <br/>
            <%= target.member.account_number.to_s %><br/>
          </div>
          
          <div class="pull-right text-right width-30pt p-t-10">
            <a class="label label-success font-xlarge" href="<%= transaction_path(t.id) %>" style="display: inline">
              <i class="fa fa-<%= t.eater.member == current_member ? 'plus' : 'minus' %>"></i>
              <%= number_to_currency t.value %>
            </a><br/><br/>

            <a class="label label-default" href="<%= transaction_path(t.id) %>" style="display: inline"><%= t.status.upcase %></a><br/>
            <small><%= t.completed_date ||= "N/A" %></small><br/>        
          </div>
        </div>
    </div>
    <%- end %>
  </div>
  </dd>
  </dl>
</div>

app/views/dashboard/_regular_member.html.erb
    <section class="content-section dashboard-public margin-top-50">
      <div class="container paddingBottom-10">
        <%= render 'layouts/notice' %>
        <%- if current_member.accounts.any? and @current_account.present? %>
          <%= render 'dashboard/summary' %>
        <%- end %>
      </div>

      <div class="container paddingTop-20 paddingBottom-10">
        <div class="row no-gutters marginTop-10">
          <%- if current_member.accounts.any? %>
            <%= render 'dashboard/current_transaction' if @current_transaction.present? %>
          <%- else %>
            <%= render 'dashboard/no_accounts' %>
          <%- end %>

          <%- if current_member.accounts.any? %>
            <%= render 'dashboard/history' if @transaction_history.any? %>
          <%- end %>
        </div>
      </div>
    </section>

app/views/dashboard/_summary.html.erb
        <div class="row flex cards marginTop-10">
            <div class="col-xs-12 col-md-6 col-lg-3">
              <div class="row flex tiles-container tiles-border h-full">
                <div class="col-md-4 col-xs-5 no-padding h-full">
                  <div class="tiles green h-full content-center">
                    <i class="fa fa-chevron-circle-down"></i>
                  </div>
                </div>
                <div class="col-md-8 col-xs-7 tiles white p-10 text-center">
                  <h3 class="text-uppercase text-bold"><%= number_to_currency(@current_account.summary[:total_received].to_f) %></h3>
                  <small class="text-uppercase">Total Money</small><br/>
                  <small class="text-uppercase">Received</small>
                </div>
              </div>
            </div>
            
            <div class="col-xs-12 col-md-6 col-lg-3">
              <div class="row flex tiles-container tiles-border h-full">
                <div class="col-md-4 col-xs-5 no-padding h-full">
                  <div class="tiles green h-full content-center">
                    <i class="fa fa-chevron-circle-up"></i>
                  </div>
                </div>
                <div class="col-md-8 col-xs-7 tiles white p-10 text-center">
                  <h3 class="text-uppercase text-bold">
                    <%= number_to_currency(@current_account.summary[:total_sent].to_f) %>
                  </h3>
                  <small class="text-uppercase">Total Money</small><br/>
                  <small class="text-uppercase">Sent</small>
                </div>
              </div>
            </div>
            
            <div class="col-xs-12 col-md-6 col-lg-3">
              <div class="row flex tiles-container tiles-border h-full">
                <div class="col-md-4 col-xs-5 no-padding h-full">
                  <div class="tiles green h-full content-center">
                    <i class="fa fa-exchange"></i>
                  </div>
                </div>
                <div class="col-md-8 col-xs-7 tiles white p-10 text-center">
                  <h3 class="text-uppercase text-bold">
                    <%= @current_account.summary[:total_transaction] %>
                    <small>&nbsp; TRX's</small>
                  </h3>
                  <small class="text-uppercase">Total <br/>Transaction</small><br/>
                </div>
              </div>
            </div>
            
            <div class="col-xs-12 col-md-6 col-lg-3">
              <div class="row flex tiles-container tiles-border h-full">
                <div class="col-md-4 col-xs-5 no-padding h-full">
                  <div class="tiles green h-full content-center">
                    <i class="fa fa-user"></i>
                  </div>
                </div>
                <div class="col-md-8 col-xs-7 tiles white p-10 text-center">
                  <h3 class="text-uppercase text-bold">
                    <%= current_member.summary[:total_accounts] %>
                    <small>&nbsp; Accounts</small>
                  </h3>
                  <small class="text-uppercase">TOTAL <br/>ACCOUNT</small>
                </div>
              </div>
            </div>

        </div>

app/views/dashboard/_super_admin.html.erb
<section class="content-section dashboard-public margin-top-50">
  <%= render 'dashboard/groups', groupements: @groupements %>
</section>

app/views/dashboard/groups.html.erb
<%= render "dashboard/items/group", groupements: @groupements %>

<%- page_title 'Groupements' %>

app/views/dashboard/index.html.erb
<%= render "dashboard/roles/#{current_member.role_name}" %>

<%- page_title 'Summary' %>

app/views/dashboard/members.html.erb
<div class="spacer-90"></div>
<div class="container paddingBottom-10">
	<%= render 'layouts/notice' %>
	<h1 class="title block">Member List</h1>

	<div class="table-responsive">
	  <table class="table table-hover table-dash ">
	    <thead>
	      <tr>
	        <th>Member</th>
	        <th>Bank</th>
	        <th>Accounts</th>
	        <th>Limit</th>
	        <th>Action</th>
	      </tr>
	    </thead>
	    <tbody>
	      <%= render 'dashboard/items/member' %>
	    </tbody>
	  </table>
	</div>
</div>

<%- page_title 'Manage Members' %>