config/routes.rb
Rails.application.routes.draw do

  devise_for :members, path: '', path_names: {sign_in: '/login', sign_out: '/logout', sign_up: '/signup'}, controllers: { registrations: 'registrations' }

  
  post 'upload-receipt/:id' => 'transaction#upload_receipt', :as => :upload_receipt

  get 'transactions' => 'transaction#list', :as => :transactions
  get 'disputes' => 'transaction#disputes', :as => :disputes

  get 'transaction-receipt/:id' => 'transaction#receipt', :as => :receipt
  get 'dispute/:id' => 'transaction#dispute', :as => :dispute
  get 'transaction/:id' => 'transaction#show', :as => :transaction
  get 'transaction/:id/send-money' => 'transaction#send_money', :as => :send_money
  get 'transaction/:id/reject' => 'transaction#reject', :as => :reject
  get 'transaction/:id/confirm' => 'transaction#confirm', :as => :confirm
  get 'transaction/:id/settle' => 'transaction#settle', :as => :settle

  # Dashboard
  get  'dashboard' => 'dashboard#index', :as => :dashboard
  post 'setting' => 'dashboard#setting', :as => :setting
  get  'members' => 'dashboard#members', :as => :members
  get  'groups' => 'dashboard#groups', :as => :groups

  # Account
  get  'account/add' => 'account#add', :as => :add_account
  get  'account/:id/kick-out' => 'account#kick_out', :as => :kick_out
  post 'account/change-pool-order/:id' => 'account#change_pool_order', :as => :change_pool_order

  # Member
  post 'member/increase-accounts-limit/:id' => 'member#increase_accounts_limit', :as => :increase_accounts_limit
  get  'member/:id/edit' => 'member#edit', :as => :edit_member
  post 'member/:id' => 'member#update', :as => :update_member
  get  'member/:id' => 'member#show', :as => :member
  get  'member/:id/lock' => 'member#lock', :as => :lock_member
  get  'member/:id/complete' => 'member#complete', :as => :complete_member
  get  'add-super-user' => 'member#add_super_user', :as => :add_super_user
  
  get  'add-group' => 'member#add_group', :as => :add_group
  get  'edit-group/:id' => 'member#edit_group', :as => :edit_group
  post  'save-group' => 'member#save_group', :as => :save_group
  post  'update-group/:id' => 'member#update_group', :as => :update_group
  post  'save-super-user' => 'member#save_super_user', :as => :save_super_user

  get  'add-admin' => 'member#add_admin', :as => :add_admin
  post  'save-admin' => 'member#save_admin', :as => :save_admin


  # Pool
  get  'add-pool' => 'pool#add', :as => :add_pool
  post 'save-pool' => 'pool#save', :as => :save_pool
  get  'pool/:id/edit' => 'pool#edit', :as => :edit_pool
  post 'pool/:id/update' => 'pool#update', :as => :update_pool





  # Home
  get  'support' => 'home#support', :as => :support
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_member!

  def index
    if current_member.super_admin?
      @current_account = nil
      @groupements     = Groupement.includes(:pools => :accounts).all
      @members         = Member.all
    else 
      @groupements = [current_member.groupement].compact if current_member.group_admin?
      if @current_account.present?
        @transaction_history  = @current_account.transaction_history
        @current_transactions = @current_account.pending_transactions
        @current_transaction  = @current_transactions.pop
      end
    end
  end

  def members
    if current_member.super_admin?
      @members = Member.all
    elsif current_member.group_admin?
      @members = current_member.groupement.members rescue []
    end
  end

  def groups
    if current_member.super_admin?
      @groupements = Groupement.includes(pools: :accounts).all
    elsif current_member.group_admin?
      @groupements = [current_member.groupement.includes(:pools)].compact
    end
  end

  def setting
    @member = current_member
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def timeout_wording(t)
    distance_of_time_in_words(Date.current.in_time_zone, (t.created_at + t.timeout.seconds))
  end

  def timeout_countdown_old(t)
    (t.created_at + t.timeout.seconds).strftime("%b, %d, %Y")
  end

  def timeout_countdown(t)
    x = []
    (t.created_at + t.timeout.seconds).strftime("%Y, %m, %d, %H, %M, %S, 000").split(",").each_with_index{|a,i| i == 1 ? x << (a.to_i-1) : x << a  }
    x.join(",")
  end  
end

app/views/dashboard/items/_group.html.erb
<div class="container paddingBottom-10">
<%= render 'layouts/notice' %>
<%- for group in groupements do %>      
  <h1 class="title block"><%= group.title %></h1>

  <div class="tabbable tabs-left">
    <ul class="nav nav-tabs" role="tablist">
      <%- group.pools.each_with_index do |p,i| %>
        <li class="<%= 'active' if i.zero? %>">
          <a href="#tab-pool-<%= "#{group.id}-#{p.id}" %>" role="tab" data-toggle="tab"><%= p.title %></a>
        </li>            
      <%- end %>
      <li class="">
        <a href="#tab-pool-<%= "#{group.id}-completed" %>" role="tab" data-toggle="tab">Finished</a>
      </li>             
    </ul>
    <div class="tab-content">
      <%- group.pools.each_with_index do |p,i| %>
      <div class="tab-pane <%= 'active' if i == 0 %>" id="tab-pool-<%= "#{p.groupement.id}-#{p.id}" %>">
        <div class="table-responsive">
          <table class="table table-hover table-dash ">
            <thead>
              <tr>
                <th>Receive Order</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <%- pool_orders = (0..p.accounts.maximum(:pool_order)).to_a %>
                  <%- for a in p.accounts.includes(member: :bank).order(pool_order: :asc) do %>
                    <div class="flex group-item-separator">
                    <%= form_tag change_pool_order_path(a) do %>
                      <%= select_tag :pool_order, options_for_select(pool_orders, a.pool_order), class: 'form-control', onchange: 'this.form.submit()' %>
                    <%- end %>                         
                      <figure class="item-img m-r-10">
                        <a href="#"> &nbsp; <i class="fa fa-user text-lg"></i></a>
                      </figure>
                      <div class="item-desc">
                        <a href="#">
                          <strong><%= a.member.account_holder_name rescue "N/A" %> (<%= a.name %>)</strong>
                        </a><br>
                        <i class="fa fa-credit-card"></i> <%= a.member.bank.title rescue "N/A" %> <br/>
                        <%= a.member.account_number rescue "N/A" %> <br/>

                        <label class="label label-success label-lg">
                          <i class="fa fa-chevron-circle-up"></i>
                          <%= p.p_transactions.where(feeder_id: a.id).count %>
                        </label>
                        <label class="label label-success label-lg m-l-10">
                          <i class="fa fa-chevron-circle-down"></i>
                          <%= p.p_transactions.where(eater_id: a.id).count %>
                        </label>
                      </div>
                    </div>
                    <div class="flex pull-right">
                      
                    </div>
                  <%- end %>
                </td>               
              </tr>
              <tr>
                <td>
                  <label class="btn btn-green">
                    Amount <i class="fa fa-money"></i> <%= p.amount %>
                  </label>
                  <a href="<%= edit_pool_path(p) %>" class="btn btn-primary">
                    <i class="fa fa-edit"></i> Edit Pool
                  </a>
                  <a href="<%= edit_group_path(group) %>" class="btn btn-primary">
                    <i class="fa fa-edit"></i> Edit Group
                  </a>                       
                </td>
              </tr>
            </tbody>
          </table>

        </div>
      </div>
      <%- end %>
      <div class="tab-pane" id="tab-pool-<%= "#{group.id}-completed" %>">
        <div class="table-responsive">
          <table class="table table-hover table-dash ">
            <thead>
              <tr>
                <th>Finished Accounts</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <%- for a in group.pools.order(:position).last.accounts.completed.order(updated_at: :asc) do %>
                    <div class="flex group-item-separator">                      
                      <figure class="item-img m-r-10">
                        <a href="#"> &nbsp; <i class="fa fa-user text-lg"></i></a>
                      </figure>
                      <div class="item-desc">
                        <a href="#">
                          <strong><%= a.member.account_holder_name %> (<%= a.name %>)</strong>
                        </a><br>
                        <i class="fa fa-credit-card"></i> <%= a.member.bank.title %> <br/>
                        <%= a.member.account_number %> <br/>

                        <label class="label label-success label-lg">
                          <i class="fa fa-chevron-circle-up"></i>
                          <%= Transaction.where(feeder_id: a.id, pool_id: [group.pools.map(&:id)]).count %>
                        </label>
                        <label class="label label-success label-lg m-l-10">
                          <i class="fa fa-chevron-circle-down"></i>
                          <%= Transaction.where(eater_id: a.id, pool_id: [group.pools.map(&:id)]).count %>
                        </label>
                      </div>
                    </div>
                    <div class="flex pull-right">
                      
                    </div>
                  <%- end %>
                </td>               
              </tr>
              <tr>
              </tr>
            </tbody>
          </table>

        </div>
      </div>
    </div>
  </div>
  
<%- end %>
</div>

app/views/dashboard/items/_member.html.erb
<%- for member in @members do %>
  <tr>
    <td>
      <strong><a href="#"><%= member.full_name %></a></strong><br>
      <small>Last login : <%= member.last_sign_in_at(:short) rescue "N/A" %></small><br/>
      <%= member.email rescue "N/A" %><br/>
      <%= member.groupement.title rescue "N/A" %><br/>
      <label class="label label-default"><%= member.role_name.titleize %></label>
    </td>
    <td>
      <%= member.bank.try(:title) %><br/> 
      <%= member.account_number %> <br/>
      <%= member.account_holder_name %> <br/>
      <span class="label label-success"><i class="fa fa-chevron-circle-up"></i><%= number_to_currency member.summary[:money_sent] %></span>
      <span class="label label-success"><i class="fa fa-chevron-circle-down"></i><%= number_to_currency member.summary[:money_received] %></span>      
    </td>
    <td>
      <ul class="" style="list-style-type: none;padding-left: 0px">
        <%- for account in member.accounts do %>                    
        <li style="margin-left: 0px;padding-bottom: 5px;">
          <i class="fa fa-user"></i>
          <a href="#"><%= account.name %></a>
          <label class="label label-success label-lg">
            <i class="fa fa-chevron-circle-up"></i>
            <%= number_to_currency account.summary[:total_sent] %>
          </label>
          <label class="label label-success label-lg m-l-10">
            <i class="fa fa-chevron-circle-down"></i>
            <%= number_to_currency account.summary[:total_received] %>
          </label>          
        </li>
        <%- end %>
      </ul>

    </td>
    <td>
      <%= form_tag increase_accounts_limit_path(member) do %>
        <%= text_field_tag :accounts_limit, member.accounts_limit, class: 'form-control', style: 'width:100px'  %>
        <%= submit_tag "increase limit", class: 'btn btn-primary', style: 'margin-top:5px;width:100px' %>
      <%- end %>
    </td>
    <td>
      <a href="<%= member_path(member) %>" class="btn btn-white width-80">
        <i class="fa fa-expand"></i>
        &nbsp; more <br/>
      </a>                  
      <br/>
      <a href="<%= edit_member_path(member) %>" class="btn btn-white width-80">
        <i class="fa fa-pencil"></i>
        &nbsp; edit <br/>
      </a>
      <br/>
      <a href="<%= lock_member_path(member) %>" class="btn btn-white width-80">
        <%- if member.access_locked? %>
          <i class="fa fa-unlock-alt"></i>
          &nbsp; unlock <br/>
        <%- else %>
          <i class="fa fa-lock"></i>
          &nbsp; lock <br/>                 
        <%- end %>
      </a>                  
    </td>
  </tr>
<%- end %>