config/routes.rb
Rails.application.routes.draw do

  devise_for :members, path: '', path_names: {sign_in: '/login', sign_out: '/logout', sign_up: '/signup'}, controllers: { registrations: 'registrations' }

  
  post 'upload-receipt/:id' => 'transaction#upload_receipt', :as => :upload_receipt

  get 'transactions' => 'transaction#list', :as => :transactions
  get 'disputes' => 'transaction#disputes', :as => :disputes

  get 'transaction-receipt/:id' => 'transaction#receipt', :as => :receipt
  get 'dispute/:id' => 'transaction#dispute', :as => :dispute
  get 'transaction/:id' => 'transaction#show', :as => :transaction
  get 'transaction/:id/send-money' => 'transaction#send_money', :as => :send_money
  get 'transaction/:id/reject' => 'transaction#reject', :as => :reject
  get 'transaction/:id/confirm' => 'transaction#confirm', :as => :confirm
  get 'transaction/:id/settle' => 'transaction#settle', :as => :settle

  # Dashboard
  get  'dashboard' => 'dashboard#index', :as => :dashboard
  post 'setting' => 'dashboard#setting', :as => :setting
  get  'members' => 'dashboard#members', :as => :members
  get  'groups' => 'dashboard#groups', :as => :groups

  # Account
  get  'account/add' => 'account#add', :as => :add_account
  get  'account/:id/kick-out' => 'account#kick_out', :as => :kick_out
  post 'account/change-pool-order/:id' => 'account#change_pool_order', :as => :change_pool_order

  # Member
  post 'member/increase-accounts-limit/:id' => 'member#increase_accounts_limit', :as => :increase_accounts_limit
  get  'member/:id/edit' => 'member#edit', :as => :edit_member
  post 'member/:id' => 'member#update', :as => :update_member
  get  'member/:id' => 'member#show', :as => :member
  get  'member/:id/lock' => 'member#lock', :as => :lock_member
  get  'member/:id/complete' => 'member#complete', :as => :complete_member
  get  'add-super-user' => 'member#add_super_user', :as => :add_super_user
  
  get  'add-group' => 'member#add_group', :as => :add_group
  get  'edit-group/:id' => 'member#edit_group', :as => :edit_group
  post  'save-group' => 'member#save_group', :as => :save_group
  post  'update-group/:id' => 'member#update_group', :as => :update_group
  post  'save-super-user' => 'member#save_super_user', :as => :save_super_user

  get  'add-admin' => 'member#add_admin', :as => :add_admin
  post  'save-admin' => 'member#save_admin', :as => :save_admin


  # Pool
  get  'add-pool' => 'pool#add', :as => :add_pool
  post 'save-pool' => 'pool#save', :as => :save_pool
  get  'pool/:id/edit' => 'pool#edit', :as => :edit_pool
  post 'pool/:id/update' => 'pool#update', :as => :update_pool





  # Home
  get  'support' => 'home#support', :as => :support
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/concerns/transactions/status.rb
module Transactions
	module Status
		extend ActiveSupport::Concern

		def confirmed?
			(sender_confirmed? and receiver_confirmed?) and admin_confirmed?
		end

		def new_transaction?
			! confirmed?
		end

		def timeout_datetime
			(self.created_at + self.timeout.seconds).to_datetime
		end

		def timed_out?
		 	timeout_datetime < Date.current.in_time_zone
		end

		def confirm!
			self.admin_confirmed = true
			self.disputed = false
			self.failed = false
			self.disputed = false
		end

		def fail!
			self.failed = true
			self.disputed = false
			self.admin_confirmed = false
			self.sender_confirmed = false
			self.receiver_confirmed = false
		end

		def sender_confirm!
			self.sender_confirmed = true
		end

		def receiver_confirm!
			self.receiver_confirmed = true
		end

		def dispute!
			self.disputed = true
			self.admin_confirmed = false
			self.failed = false
		end

		def status
			if confirmed?
			  "transaction completed"
			elsif disputed?
				"under dispute"
			elsif failed?
				"transaction failed"
			elsif sender_confirmed?
			  "sender confirmed"
			elsif receiver_confirmed?
			  "receiver confirmed"
			else
			  "new transaction"
			end
		end
	end
end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  before_action :authenticate_member!

  def list
    if current_member.super_admin?
      @transactions = Transaction.order(updated_at: :desc)
    elsif current_member.group_admin?
      @transactions = Transaction.where(pool_id: current_member.groupement.pools.map(&:id)).order(updated_at: :desc) rescue []
    end
  end

  def disputes
    if current_member.super_admin?
      @transactions = Transaction.disputed
    elsif current_member.group_admin?
      @transactions = Transaction.disputed.where(pool_id: current_member.groupement.pools.map(&:id)) rescue []
    end    
  end

  def dispute
    @transaction = Transaction.where(id: params[:id]).first

    if @transaction.present? and @transaction.dispute_allowed? and (@transaction.eater.member == current_member or @transaction.feeder.member == current_member)
      @transaction.dispute!
      @transaction.save
      @transaction.notify_disputed
      redirect_to transaction_path(@transaction), notice: 'Transaction has been disputed'
    else
      redirect_to transaction_path(@transaction), notice: "Unable to dispute transaction: #{@transaction.errors.to_a.first}"
    end
  end

  def show
    if current_member.regular_member?
      @transaction = Transaction.by_member(current_member).where(id: params[:id]).first
    else
      @transaction = Transaction.where(id: params[:id]).first
    end
  end

  def settle
    if current_member.regular_member?
      @transaction = Transaction.by_member(current_member).where(id: params[:id]).first
    else
      @transaction = Transaction.where(id: params[:id]).first
    end

    if @transaction.disputed?
      redirect_to transaction_path(@transaction), notice: "Transaction is currently under dispute"
    else
      @transaction.receiver_confirmed = true
      @transaction.admin_confirmed    = true
      @transaction.receiver_confirmed_at = DateTime.now

      if @transaction.save
        @transaction.notify_receiver_confirmed
        notice =  "You've successfully confirmed settlement of the transfer"
      else
        notice = "Unable to confirm settlement: #{@transaction.errors.to_a.first}"
      end
      redirect_to transaction_path(@transaction), notice: notice
    end
  end

  def confirm
    unless current_member.regular_member?
      @transaction = Transaction.where(id: params[:id]).first
      if @transaction.present?
        @transaction.admin_confirmed    = true
        @transaction.sender_confirmed   = true
        @transaction.receiver_confirmed = true
        @transaction.completed_date     = Date.today
        @transaction.failed   = false
        @transaction.disputed = false
        if @transaction.save
          @transaction.notify_resolved
          redirect_to transaction_path(@transaction), notice: 'Transaction has been confirmed'
        else
          redirect_to transaction_path(@transaction), notice: "Unable to confirm transaction: #{@transaction.errors.to_a.first}"
        end
      else
        redirect_to transaction_path(@transaction), notice: "Transaction not found or not authorized"
      end
    end
  end

  def reject
    unless current_member.regular_member?
      @transaction = Transaction.where(id: params[:id]).first
      if @transaction.present?
        @transaction.admin_confirmed = false
        @transaction.disputed        = false
        @transaction.failed          = true

        if @transaction.save
          eater = @transaction.eater
          eater.number_associations_left = eater.number_associations_left + 1
          eater.pool_order = eater.pool.accounts.minimum(:pool_order).to_i - 1
          eater.save

          @transaction.notify_failed
          redirect_to transaction_path(@transaction), notice: 'Transaction has been rejected'
        else
          redirect_to transaction_path(@transaction), notice: "Unable to confirm transaction: #{@transaction.errors.to_a.first}"
        end
      else
        redirect_to transaction_path(@transaction), notice: "Transaction not found or not authorized"
      end
    end
  end

  def send_money
    @transaction = Transaction.by_member(current_member).where(id: params[:id]).first
  end

  def upload_receipt
    if current_member.regular_member? or current_member.group_admin?
      @transaction = Transaction.by_member(current_member).where(id: params[:id]).first 
      
      @transaction.sender_receipt = params[:receipt]
      @transaction.sender_confirmed = true
      @transaction.sender_confirmed_at = DateTime.now

      if @transaction.save
        @transaction.notify_sender_confirmed
        redirect_to transaction_path(@transaction.id), notice: "You have confirmed sending money to receiver"
      else
        redirect_to transaction_path(@transaction.id), notice: "Unable to save receipt: #{@transaction.errors.to_a.first}"
      end
    end
  end

  def receipt
    if current_member.regular_member?
      @transaction = Transaction.by_member(current_member).where(id: params[:id]).first
    else
      @transaction = Transaction.where(id: params[:id]).first
    end
    if @transaction.present? and @transaction.sender_receipt.file.present?
      send_file File.open(@transaction.sender_receipt.file.file) 
    else
      redirect_to :back, notice: "Receipt is not available at the moment"
    end
  end

end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/transaction/disputes.html.erb
      <div class="container padding-top-90">
        <div class="row">
          <div class="col-md-12">
            <%= render 'layouts/notice' %>

              <h1 class="title block">Disputes</h1>

              <%- for transaction in @transactions do %>
              <hr/>
              <div class="row">
              <div class="col-md-12">
                <div class="tiles white">
                  <div class="row">
                      <div class="col-md-4 col-sm-4">
                        <p class="no-margin">RECEIVER</p>
                        <h4>
                          <span class="item-count">
                            <%= transaction.eater.member.full_name %>
                          </span> 
                        </h4>
                        <p>
                          <i class="fa fa-bank"></i>&nbsp;
                          <%= transaction.eater.member.bank.title rescue "N/A" %> <br/>
                          <%= transaction.eater.member.account_number %> <br/>
                          <%= transaction.eater.member.account_holder_name %>
                          <br/><br/>
                          <i class="fa fa-envelope"></i>&nbsp; <%= transaction.eater.member.email %><br/>
                          <i class="fa fa-phone"></i>&nbsp; <%= transaction.eater.member.phone_number %>                                                 
                        </p>
                      </div>
                      <div class="col-md-4">
                        <p class="semi-bold">SENDER</p>
                        <h4>
                          <span class="item-count">
                            <%= transaction.feeder.member.full_name %>
                          </span>
                        </h4>
                        <p>
                          <i class="fa fa-bank"></i>&nbsp;
                          <%= transaction.feeder.member.bank.title %> <br/>
                          <%= transaction.feeder.member.account_number %> <br/>
                          <%= transaction.feeder.member.account_holder_name %>  
                          <br/><br/>
                          <i class="fa fa-envelope"></i>&nbsp; <%= transaction.feeder.member.email %><br/>
                          <i class="fa fa-phone"></i>&nbsp; <%= transaction.feeder.member.phone_number %>                       
                        </p>
                      </div>

                      <div class="col-md-4">
                        <p class="semi-bold">Amount</p>
                        <h3><span class="item-count semi-bold">
                          <span class="label label-success label-lg"><%= number_to_currency transaction.value %></span>
                          <span class="label label-danger label-lg"><%= time_ago_in_words transaction.timeout_datetime.to_s(:short) %></span>
                        </h3>
                        <span>
                          <i class="fa fa-clock-o"></i>
                          <%= transaction.timeout_datetime.to_s(:short) %></span><br/>
                      </div>

                      <div class="clearfix"></div>
                  </div>
                  <h5 class="semi-bold m-t-30 m-l-30"></h5>
                  <table class="table no-more-tables m-t-20 m-l-20 m-b-30">
                    <thead style="display:none">
                      <tr>
                        <th style="width:45%"></th>
                        <th style="width:45%"></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td class="v-align-middle red pull-left">
                        </td>
                        <td class="v-align-middle bold text-success pull-right">
                          <%- if transaction.sender_receipt.present? and transaction.sender_receipt.file.present? %>
                            <a href="<%= receipt_path(transaction) %>" class="btn btn-white"><i class="fa fa-file"></i>&nbsp;show receipt</a>
                          <%- end %>
                          <a href="<%= confirm_path(transaction) %>" class="btn btn-white"><i class="fa fa-check"></i>&nbsp;confirm payment</a>
                          <a href="<%= reject_path(transaction) %>" class="btn btn-white"><i class="fa fa-times"></i>&nbsp;reject payment</a>
			  <%- unless transaction.eater.kicked_out? %>
                          <a href="<%= kick_out_path(transaction.eater) %>" class="btn btn-white"><i class="fa fa-long-arrow-right"></i>&nbsp;kick receiver</a>    
		          <%- else %>

				  <label class="label label-default">RECEIVER KICKED OUT</label>
		          <%- end %>

			  <%- unless transaction.feeder.kicked_out? %>
                          <a href="<%= kick_out_path(transaction.feeder) %>" class="btn btn-white"><i class="fa fa-long-arrow-right"></i>&nbsp;kick sender</a>                                              
			  <%- else %>
				  <label class="label label-default">SENDER KICKED OUT</label>
		          <%- end %>
                        </td>                        
                      </tr>

                    </tbody>
                  </table>
                </div>
              </div>
            </div>
              <%- end %>
          </div>
        </div>
        
      </div>
      </div>

<%- page_title 'Transactions' %>

app/views/transaction/list.html.erb
      <div class="container padding-top-90">
        <div class="row">
          <div class="col-md-12">
            <%= render 'layouts/notice' %>
            <h1 class="title block">Transactions</h1>

              <%- for transaction in @transactions do %>
              <hr/>
              <div class="row">
              <div class="col-md-12">
                <div class="tiles white">
                  <div class="row">
                      <div class="col-md-4 col-sm-4 p-t-10" style="background-color: #F76F76">
                        <p class="no-margin">RECEIVER</p>
                        <h4>
                          <span class="item-count text-white">
                            <i class="fa fa-user"></i>&nbsp;<%= transaction.eater.name rescue "N/A" %> (<%= transaction.eater.member.full_name rescue "N/A" %>)
                          </span> 
                        </h4>
                        <p class="text-white">
                          <i class="fa fa-bank"></i>&nbsp;
                          <%= transaction.eater.member.bank.title rescue "N/A" %> <br/>
                          <%= transaction.eater.member.account_number rescue "N/A" %> <br/>
                          <%= transaction.eater.member.account_holder_name rescue "N/A" %>
                        </p>
                      </div>
                      <div class="col-md-4 p-t-10">
                        <p class="semi-bold">SENDER</p>
                        <h4>
                          <span class="item-count">
                            <i class="fa fa-user"></i>&nbsp;<%= transaction.feeder.name  rescue "N/A" %> (<%= transaction.feeder.member.full_name  rescue "N/A"%>)
                          </span>
                        </h4>
                        <p>       
                          <i class="fa fa-bank"></i>&nbsp;
                          <%= transaction.feeder.member.bank.title rescue "N/A" %> <br/>
                          <%= transaction.feeder.member.account_number rescue "N/A" %> <br/>
                          <%= transaction.feeder.member.account_holder_name rescue "N/A" %>                          
                        </p>
                      </div>

                      <div class="col-md-4 p-t-10">
                        <p class="semi-bold">AMOUNT</p>
                        <h3><span class="item-count semi-bold">
                          <span class="label label-success label-lg"><%= number_to_currency transaction.value %></span>
                          <span class="label label-danger label-lg"><%= transaction.pool.title %></span>
                        </h3>
                        <span>
                          <i class="fa fa-clock-o"></i>
                          <%= transaction.timeout_datetime.to_s(:short) %></span><br/>
                      </div>

                      <div class="clearfix"></div>
                  </div>
                  <table class="table no-more-tables m-l-20">
                    <thead style="display:none">
                      <tr>
                        <th style="width:45%"></th>
                        <th style="width:45%"></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td class="v-align-middle red pull-left">

                        </td>
                        <td class="v-align-middle bold text-success pull-right">
                          <span class="label label-default" style="font-size: 14px">
                            <i class="fa fa-exchange"></i>
                            <%= transaction.status.upcase %>
                          </span>
                        </td>                        
                      </tr>

                    </tbody>
                  </table>
                </div>
              </div>
            </div>
              <%- end %>
          </div>
        </div>
        
      </div>
      </div>

<%- page_title 'Transactions' %>

app/views/transaction/send_money.html.erb
    <section class="content-section dashboard margin-top-50">
      <br/>
      <div class="container p-0">
        <div class="row">
          <div class="card col-12 col-sm-8 offset-sm-2">
            <div class="card-panel bg-white  text-grey p-0">
            </div>
          </div>
        </div>
      </div>
      <%- target = @transaction.eater.member == current_member ? @transaction.feeder : @transaction.eater %>
      <div class="container p-0">
        <div class="row">
          <div class="card col-12 col-sm-8 offset-sm-2">
            <%= render 'layouts/notice' %>
            <h1 class="title block">Send Money</h1>

            <div class="row">
              <div class="col-12 p-0">
                <ul class="details list-group">
                  <li class="list-group-item">
                    <div class="container-fluid no-gutters padding-0">
                      <div class="row no-gutters">
                      <div class="col-5">Amount</div>
                      <div class="col-7"><label class="details-text"><%= number_to_currency @transaction.value %> </label></div>
                      </div>
                    </div>
                  </li>                
                  <li class="list-group-item">
                    <div class="container-fluid no-gutters padding-0">
                      <div class="row no-gutters">
                      <div class="col-5">Account Name</div>
                      <div class="col-7"><label class="details-text"><%= target.member.try(:account_holder_name) %> </label></div>
                      </div>
                    </div>
                  </li>
                  <li class="list-group-item">
                    <div class="container-fluid no-gutters padding-0">
                      <div class="row no-gutters">
                      <div class="col-5">Bank Name</div>
                      <div class="col-7 text-uppercase"><label class="details-text"><%= target.member.bank.title %></label></div>
                      </div>
                    </div>
                  </li>
                  <li class="list-group-item">
                    <div class="container-fluid no-gutters padding-0">
                      <div class="row no-gutters">
                      <div class="col-5">Account Number</div>
                      <div class="col-7 text-uppercase"><label class="details-text"><%= target.member.account_number %></label></div>
                      </div>
                    </div>
                  </li>
                </ul>
              </div>
            </div>

            <%= form_tag upload_receipt_path(@transaction.id), multipart: true do %>
            <div class="row">
              <div class="col-12 p-0">
                <div class="field">
                  <br/><br/>
                  <%= label_tag :transfer_receipt, 'Confirm your transaction by uploading transfer receipt', class: 'text-bold' %>
                  <%= file_field_tag :receipt, class: 'text-center width-100pct' %><br/>
                </div>

                <div class="actions">
                  <%= submit_tag "Confirm", class: 'btn btn-primary p-r-10' %>
                  <a class="btn btn-default p-l-20 p-r-20" href="<%= transaction_path(@transaction) %>">
                    <i class="fa fa-angle-double-left"></i>
                    Transaction Detail
                  </a>
                  <a class="btn btn-default p-l-20 p-r-20" href="<%= dashboard_path %>">
                    <i class="fa fa-angle-double-left"></i>
                    Dashboard
                  </a>                  
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>

<%- page_title 'Send Money' %>

app/views/transaction/show.html.erb
    <section class="content-section dashboard margin-top-50">
      <br/>
      <div class="container p-0">
        <div class="row">
          <div class="card col-12 col-sm-8 offset-sm-2">
          
            <div class="card-panel bg-white  text-grey p-0">
              <%= render 'layouts/notice' %>
            </div>
          </div>
        </div>
      </div>
      <%- target = @transaction.eater.member == current_member ? @transaction.feeder : @transaction.eater %>
      <div class="container p-0">
        <div class="row">
          <div class="card col-12 col-sm-8 offset-sm-2">
            <div class="label-success pull-right p-10 text-center">
              <span class="pull-left"><%= @transaction.status %></span><br/>
              <span class="font-35"><%= number_to_currency @transaction.value %>&nbsp;<i class="fa fa-chevron-circle-<%= @transaction.eater.member == current_member ? "left" : "right" %> pull-right"></i></span>
            </div>
          </div>
        </div>
      </div>

      <div class="container paddingBottom-10">
        <div class="row no-gutters">
          <div class="col-12 col-sm-8 offset-sm-2">
            <div class="sub-heading paddingLeft-15 paddingRight-15">
              <h4 class="text-bold">Account Details</h4>
            </div>
            <div class="row">
              <div class="col-12">
                <ul class="details list-group">
                  <li class="list-group-item">
                    <div class="container-fluid no-gutters padding-0">
                      <div class="row no-gutters">
                      <div class="col-5">Name</div>
                      <div class="col-7"><label class="details-text"><%= target.member.try(:account_holder_name) %> </label></div>
                      </div>
                    </div>
                  </li>
                  <li class="list-group-item">
                    <div class="container-fluid no-gutters padding-0">
                      <div class="row no-gutters">
                      <div class="col-5">Bank Name</div>
                      <div class="col-7 text-uppercase"><label class="details-text"><%= target.member.bank.title rescue "N/A" %></label></div>
                      </div>
                    </div>
                  </li>
                  <li class="list-group-item">
                    <div class="container-fluid no-gutters padding-0">
                      <div class="row no-gutters">
                      <div class="col-5">Account Number</div>
                      <div class="col-7 text-uppercase"><label class="details-text"><%= target.member.try(:account_number) %></label></div>
                      </div>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
            <div class="container paddingBottom-10">
              <%- unless @transaction.confirmed? %>
              <div class="sub-heading paddingLeft-15 paddingRight-15">
                <h4 class="text-bold">Contact Details</h4>
              </div>
              <div class="row">
                <div class="col-12">
                  <ul class="details list-group">
                    <li class="list-group-item">
                      <div class="container-fluid no-gutters padding-0">
                        <div class="row no-gutters">
                        <div class="col-5">Phone Number</div>
                        <div class="col-7"><label class="details-text"><%= target.member.phone_number %> </label></div>
                        </div>
                      </div>
                    </li>
                    <li class="list-group-item">
                      <div class="container-fluid no-gutters padding-0">
                        <div class="row no-gutters">
                        <div class="col-5">Email</div>
                        <div class="col-7"><label class="details-text"><%= target.member.email %></label></div>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
              <%- end %>
              <div class="row marginTop-20">
                <div class="col-12">
                  <div class="details btn-group mr-2" role="group">
                    <%- if current_member.accounts.include? @transaction.feeder %>

                      <%- if !@transaction.sender_confirmed? %>
                        <a href="<%= send_money_path(@transaction.id) %>" class="btn btn-primary m-r-10">
                          <i class="fa fa-chevron-circle-right"></i>
                          Send money
                        </a>
                      <%- else %>
                        <a href="<%= send_money_path(@transaction.id) %>" class="btn btn-default m-r-10">
                          <i class="fa fa-angle-up"></i>
                          Re-upload receipt
                        </a>
                      <%- end %>

                    <%- else %>

                      <%- if !@transaction.receiver_confirmed? and @transaction.sender_confirmed? %>
                      <a href="<%= settle_path(@transaction.id) %>" class="btn btn-primary m-r-10">
                        <i class="fa fa-check"></i>
                        Confirm settlement
                      </a>
                      <%- end %>

                    <%- end %>

                    <%- if @transaction.dispute_allowed? %>
                      <a href="<%= dispute_path(@transaction.id) %>" class="btn btn-default m-r-10">
                        <i class="fa fa-random"></i>
                        Dispute transaction
                      </a> 
                    <%- end %>

                    <%- if @transaction.sender_receipt.url.present? %>
                    <a href="<%= receipt_path @transaction %>" class="btn btn-default m-r-10">
                      <i class="fa fa-file"></i>
                      Download receipt
                    </a>
                    <%- end %>
                    <a class="btn btn-default p-l-20 p-r-20" href="<%= dashboard_path %>">
                      <i class="fa fa-angle-double-left"></i>
                      Dashboard
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

<%- page_title 'Transaction detail' %>