config/routes.rb
Rails.application.routes.draw do

  devise_for :members, path: '', path_names: {sign_in: '/login', sign_out: '/logout', sign_up: '/signup'}, controllers: { registrations: 'registrations' }

  
  post 'upload-receipt/:id' => 'transaction#upload_receipt', :as => :upload_receipt

  get 'transactions' => 'transaction#list', :as => :transactions
  get 'disputes' => 'transaction#disputes', :as => :disputes

  get 'transaction-receipt/:id' => 'transaction#receipt', :as => :receipt
  get 'dispute/:id' => 'transaction#dispute', :as => :dispute
  get 'transaction/:id' => 'transaction#show', :as => :transaction
  get 'transaction/:id/send-money' => 'transaction#send_money', :as => :send_money
  get 'transaction/:id/reject' => 'transaction#reject', :as => :reject
  get 'transaction/:id/confirm' => 'transaction#confirm', :as => :confirm
  get 'transaction/:id/settle' => 'transaction#settle', :as => :settle

  # Dashboard
  get  'dashboard' => 'dashboard#index', :as => :dashboard
  post 'setting' => 'dashboard#setting', :as => :setting
  get  'members' => 'dashboard#members', :as => :members
  get  'groups' => 'dashboard#groups', :as => :groups

  # Account
  get  'account/add' => 'account#add', :as => :add_account
  get  'account/:id/kick-out' => 'account#kick_out', :as => :kick_out
  post 'account/change-pool-order/:id' => 'account#change_pool_order', :as => :change_pool_order

  # Member
  post 'member/increase-accounts-limit/:id' => 'member#increase_accounts_limit', :as => :increase_accounts_limit
  get  'member/:id/edit' => 'member#edit', :as => :edit_member
  post 'member/:id' => 'member#update', :as => :update_member
  get  'member/:id' => 'member#show', :as => :member
  get  'member/:id/lock' => 'member#lock', :as => :lock_member
  get  'member/:id/complete' => 'member#complete', :as => :complete_member
  get  'add-super-user' => 'member#add_super_user', :as => :add_super_user
  
  get  'add-group' => 'member#add_group', :as => :add_group
  get  'edit-group/:id' => 'member#edit_group', :as => :edit_group
  post  'save-group' => 'member#save_group', :as => :save_group
  post  'update-group/:id' => 'member#update_group', :as => :update_group
  post  'save-super-user' => 'member#save_super_user', :as => :save_super_user

  get  'add-admin' => 'member#add_admin', :as => :add_admin
  post  'save-admin' => 'member#save_admin', :as => :save_admin


  # Pool
  get  'add-pool' => 'pool#add', :as => :add_pool
  post 'save-pool' => 'pool#save', :as => :save_pool
  get  'pool/:id/edit' => 'pool#edit', :as => :edit_pool
  post 'pool/:id/update' => 'pool#update', :as => :update_pool





  # Home
  get  'support' => 'home#support', :as => :support
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<form class="form-inline float-right">
  <%- if member_signed_in? %>
    <div class="dropdown header hidden-sm-down">
      <a class="btn btn-default-clear font-bold btn-font-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-user"></i>
        <%- if @current_account.present? %>
          <%= @current_account.name %>
        <%- else %>
          Accounts
        <%- end %>
      </a>
      <div class="dropdown-menu scrollable-menu" aria-labelledby="dropdownMenu2">
        <%- for a in current_member.accounts do %>
          <%- unless (@current_account.present? and a == @current_account) %>
            <a href="<%= dashboard_path(acc: a.name) %>" class="dropdown-item">
              <i class="fa fa-chevron-right"></i>&nbsp; <%= a.name %>
            </a>          
          <%- end %>
        <%- end %>

        <%- if current_member.can_add_account? %>
        <a href="<%= add_account_path %>" class="dropdown-item">
          <i class="fa fa-plus"></i>&nbsp; Add Account
        </a>
        <%- end %>
        
        <a href="<%= edit_member_registration_path %>" class="dropdown-item">
          <i class="fa fa-gear"></i>&nbsp; Account Settings
        </a>
      </div>
    </div>
    <a href="<%= destroy_member_session_path %>" class="btn btn-default-clear font-bold btn-font-sm nav-top-item">
      <i class="fa fa-key"></i> Logout
    </a>
  <%- else %>
    <a href="<%= new_member_session_path %>" class="btn btn-default-clear font-bold btn-font-sm nav-top-item">
      <i class="fa fa-key"></i> Login
    </a>
    <a href="<%= new_member_registration_path %>" class="btn btn-default-clear font-bold btn-font-sm nav-top-item">
      <i class="fa fa-user"></i> Sign up
    </a>
  <%- end %>
</form>

app/views/layouts/_notice.html.erb
<%- if notice.present? %>
<div class="alert alert-success">
	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	<%= notice %>
</div>
<%- end %>

<%- if alert.present? %>
<div class="alert alert-warning">
	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	<%= alert %>
</div> 
<%- end %>

app/views/layouts/_sidebar.html.erb
    <div class="aside">
        <div class="aside-header">
            Menu
        </div>
        <div class="aside-contents" id="asideMenu">
            <ul class="list-group">
              <li class="list-group-item dropdown">
                <%- if !member_signed_in? or (member_signed_in? and !current_member.super_admin?) %>
                <a href="#" data-toggle="collapse" data-target="#list01" data-parent="#asideMenu"><i class="fa fa-user" aria-hidden="true"></i> Accounts</a>
                <%- end %>
                <ul id="list01" class="sublist-item collapse clearfix">

                  <%- if member_signed_in? %>
                    <%- if !current_member.super_admin? %>
                      <%- for account in current_member.accounts do %>
                        <li class="">
                          <a href="<%= dashboard_path(acc: account.name) %>">
                            <i class="fa fa-chevron-right <%= 'fa-chevron-circle-right' if account.name == @current_account.name  rescue "" %>"></i>
                            <%= account.name %>
                          </a>
                        </li>
                      <%- end %>


                      <%- if current_member.can_add_account? %>
                      <li class="">
                        <a href="<%= add_account_path %>">
                          <i class="fa fa-plus"></i>
                          Add Account
                        </a>
                      </li>
                      <%- end %>


                    <%- end %>
                  <%- else %>
                    <li class="">
                      <a href="<%= new_member_session_path %>">
                        Login
                      </a>
                    </li>
                  <%- end %>

                </ul>
              </li>
              <%- if member_signed_in? %>
                <%- unless current_member.regular_member? %>
                  <%- unless current_member.group_admin? %>
                  <li class="list-group-item">
                    <a href="<%= transactions_path %>"><i class="fa fa-exchange" aria-hidden="true"></i> Transactions</a>
                  </li>
                  <%- end %>
                  <li class="list-group-item">
                    <a href="<%= disputes_path %>"><i class="fa fa-random" aria-hidden="true"></i> Disputes <label class="label label-default">
                      <%- if current_member.super_admin? %>
                        <%= Transaction.disputed.count %>
                      <%- else %>
                        <%= Transaction.disputed.where(pool_id: current_member.groupement.pools.map(&:id)).count %>
                      <%- end %>

                    </label></a>
                  </li>
                  <%- unless current_member.group_admin? %>
                  <li class="list-group-item">
                    <a href="<%= members_path %>"><i class="fa fa-users" aria-hidden="true"></i> Members</a>
                  </li>
                    <%- if current_member.super_admin? or current_member.group_admin? %>
                      <li class="list-group-item">
                        <a href="<%= groups_path %>"><i class="fa fa-clone" aria-hidden="true"></i> Groupements</a>
                      </li>

                      <li class="list-group-item dropdown">
                        <a href="#" data-toggle="collapse" data-target="#list02" data-parent="#asideMenu"><i class="fa fa-chevron-right" aria-hidden="true"></i> Add More..</a>

                        <ul id="list02" class="sublist-item collapse clearfix">
                            <li class="list-group-item">
                              <a href="<%= add_admin_path %>"><i class="fa fa-plus" aria-hidden="true"></i> Add Super/Group Admin</a>
                            </li>                                                  
                            <li class="list-group-item">
                              <a href="<%= add_super_user_path %>"><i class="fa fa-plus" aria-hidden="true"></i> Add Super User</a>
                            </li>
                            <li class="list-group-item">
                              <a href="<%= add_group_path %>"><i class="fa fa-plus" aria-hidden="true"></i> Add Groupement</a>
                            </li>                            
                            <li class="list-group-item">
                              <a href="<%= add_pool_path %>"><i class="fa fa-plus" aria-hidden="true"></i> Add Pool</a>
                            </li>
                        </ul>
                      </li>
                    <%- end %>
                    <%- end %>
                <%- end %>
                <li class="list-group-item">
                  <a href="<%= edit_member_registration_path %>"><i class="fa fa-cog" aria-hidden="true"></i>Account Settings</a>
                </li>
              <%- end %>

              <li class="list-group-item">
                <a href="<%= support_path %>"><i class="fa fa-question-circle" aria-hidden="true"></i>Support / FAQ</a>
              </li>
            </ul>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <title>PlayKutu | <%= yield(:title).to_s.blank? ? "Welcome to PlayKutu" : yield(:title) %></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta content="PlayKutu" name="description" />
    <meta content="PlayKutu" name="author" />

    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: :all %>
  </head>
  

  <body class="bg--white">
    <div class="pageload">
        <div class="loader"></div>
        <div class="text-loader">loading...</div>
    </div>

    <%= render 'layouts/sidebar' %>
    <div class="aside-backdrop"></div>

    <header class="header--white">
      <div class="navbar navbar-inverse bg-default container">
        <div class="container-fluid no-gutters container-no-pad">
          <div class="row no-gutters">
            <div class="col-md-5 col-lg-5 col-sm-5 col-6 text-left text-left-xs">
              <button class="navbar-toggler" type="button" onclick="$('.aside').asidebar('open')" aria-label="Toggle navigation">
                <span class="menu-logo"></span>
              </button>
              <a class="navbar-brand strong-logo" href="<%= root_path %>">
                PlayKutu
              </a>
            </div>
            <div class="col-md-7 col-lg-7 col-sm-7 col-6">
              <%= render 'layouts/nav' %>       
            </div>
          </div>
        </div>
      </div>
    </header>
    
    <div class="wrap-content">
      <%= yield %>
      <div id="push"></div>
    </div>

    <footer id="footer" class="text-muted footer-section navbar-fixed-bottom"> 
      <div class="container">   
        <div class="row">
          <div class="col text-center">
            <small>Copyright &copy; 2017. PlayKutu.com</small>
          </div>
        </div>
      </div>
    </footer>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>